"""WeatherStation & Weather tables

Revision ID: c77126705deb
Revises: 
Create Date: 2023-04-17 21:55:29.060443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c77126705deb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_station',
    sa.Column('id', sa.String(), nullable=False, comment='The Meteostat ID of the weather station'),
    sa.Column('name', sa.String(), nullable=False, comment='The English name of the weather station'),
    sa.Column('country', sa.String(), nullable=False, comment='The ISO 3166-1 alpha-2 country code of the weather station'),
    sa.Column('region', sa.String(), nullable=True, comment='The ISO 3166-2 state or region code of the weather station'),
    sa.Column('wmo', sa.String(), nullable=True, comment='The WMO ID of the weather station'),
    sa.Column('icao', sa.String(), nullable=True, comment='The ICAO ID of the weather station'),
    sa.Column('latitude', sa.Float(), nullable=False, comment='The latitude of the weather station'),
    sa.Column('longitude', sa.Float(), nullable=False, comment='The longitude of the weather station'),
    sa.Column('elevation', sa.Float(), nullable=True, comment='The elevation of the weather station in meters above sea level'),
    sa.Column('timezone', sa.String(), nullable=True, comment='The time zone of the weather station\t'),
    sa.Column('hourly_start', sa.DateTime(), nullable=True, comment='The first day on record for hourly data'),
    sa.Column('hourly_end', sa.DateTime(), nullable=True, comment='The last day on record for hourly data'),
    sa.Column('daily_start', sa.DateTime(), nullable=True, comment='The first day on record for daily data'),
    sa.Column('daily_end', sa.DateTime(), nullable=True, comment='The last day on record for daily data'),
    sa.Column('monthly_start', sa.DateTime(), nullable=True, comment='The first day on record for monthly data'),
    sa.Column('monthly_end', sa.DateTime(), nullable=True, comment='The last day on record for monthly data'),
    sa.Column('distance', sa.Float(), nullable=True, comment='Distance. Comes from station.nearby function'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weather',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station', sa.String(), nullable=False, comment='The Meteostat ID of the weather station (only if query refers to multiple stations)'),
    sa.Column('time', sa.DateTime(), nullable=False, comment='The datetime of the observation\t'),
    sa.Column('temp', sa.Float(), nullable=False, comment='The air temperature in °C'),
    sa.Column('dwpt', sa.Float(), nullable=True, comment='The dew point in °C'),
    sa.Column('rhum', sa.Float(), nullable=False, comment='The relative humidity in percent (%)'),
    sa.Column('prcp', sa.Float(), nullable=False, comment='The one hour precipitation total in mm'),
    sa.Column('snow', sa.Float(), nullable=True, comment='The snow depth in mm'),
    sa.Column('wdir', sa.Float(), nullable=False, comment='The average wind direction in degrees (°)'),
    sa.Column('wspd', sa.Float(), nullable=False, comment='The average wind speed in km/h'),
    sa.Column('wpgt', sa.Float(), nullable=True, comment='The peak wind gust in km/h'),
    sa.Column('pres', sa.Float(), nullable=True, comment='The average sea-level air pressure in hPa'),
    sa.Column('tsun', sa.Float(), nullable=True, comment='The one hour sunshine total in minutes (m)'),
    sa.Column('coco', sa.Float(), nullable=True, comment='The weather condition code'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['station'], ['weather_station.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather')
    op.drop_table('weather_station')
    # ### end Alembic commands ###
